name    'jfryman-ladder'
version '0.0.1'
source 'http://github.com/jfryman/puppet-ladder'
author 'James Fryman'
license 'Apache License Version 2.0'
summary 'Puppet Ladders'
description 'This module can be used for class autoloading based on facts'
project_page 'http://github.com/jfryman/puppet-ladder'
